package com.aos.lab3;

import java.io.Serializable;

public enum MessageType implements Serializable {

<<<<<<< HEAD
	COMPLETED, DATA, INQUIRE, REQUEST, RELEASE, GRANT, YIELD, FAILED, CHECKPOINT, RECOVERY, ACKCHECKPOINT, ACKRECOVERY, APPLICATION
=======
	COMPLETED, FAILED, CHECKPOINT, RECOVERY, ACKCHECKPOINT,
	ACKRECOVERY
>>>>>>> ab6ac2225f4361418415f1d176ff5d12a841b81a

}
